[phases.setup]
nixPkgs = ["gcc", "postgresql", "python39", "python39Packages.virtualenv", "pkg-config"]

[phases.install]
cmds = [
  "virtualenv venv",
  "venv/bin/pip install --upgrade pip",
  "venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "venv/bin/python -m bot.main" 