[phases.setup]
nixPkgs = ["gcc", "postgresql", "python39", "pkgconfig"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "python -m bot.main" 