[phases.setup]
nixPkgs = ["gcc", "postgresql", "python39", "python39Packages.pip", "pkg-config"]

[phases.install]
cmds = [
  "python -m ensurepip --upgrade",
  "python -m pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "python -m bot.main" 